### PR TITLE
Fix schema.rb file

### PR DESCRIPTION
**Pull request by vnegrisolo**
I ran `bundle exec rake db:migrate` after to pull code from master branch and then I got these changes on `schema.rb` file.

screen shot 2016-06-13 at 9 53 30 am

### CODE REVIEW

**Comment by vnegrisolo** [comment]
@jwworth I'm not sure about this PR, but we probably should merge this. Can you verify it please?

**Comment by jwworth** [comment]
@vnegrisolo interesting. This might be related to different Postgres versions. What Postgres version is your local database?

**Comment by vnegrisolo** [comment]
`9.5.1`

**Comment by jwworth** [comment]
Interesting. I'm running the same version, and when I migrate on this branch, it undoes these changes. I'm hesitant to merge until I understand this better.

**Comment by vnegrisolo** [comment]
Hey @jwworth so I'm closing this for now

**Pull request closed without merging**
